### ISSUE TITLE
Troubleshooting Docker version conflicts

### ISSUE THREAD

**Issue by carolynvs** [getcarina/getcarina.com#116]
`Error response from daemon: client and server don't have same version (client : X, server: Y)`

What should a user do when they encounter this message with RCS?

Part of #40

**Comment by kmsholcomb** [comment]
@carolynvs: does the dvm info you have written resolve this issue?

**Comment by carolynvs** [comment]
@kmsholcomb It does for Carina, and we've documented the error message and how to fix it in the troubleshooting guide.

**Comment by everett-toews** [comment]
Solved by: 

https://getcarina.com/docs/tutorials/troubleshooting/#error-response-from-daemon-client-and-server-don-39-t-have-same-version

https://getcarina.com/docs/tutorials/docker-version-manager/
