### ISSUE TITLE
Using other Rackspace products with RCS

### ISSUE THREAD

**Issue by zcorleissen** [getcarina/getcarina.com#19]

**Comment by carolynvs** [comment]
Cloud Databases was taken care of by #624

**Comment by everett-toews** [comment]
Another example is [Store private Docker registry images on Rackspace Cloud Files](https://getcarina.com/docs/tutorials/registry-on-cloud-files/)

As these tutorials (and others) demonstrate, products are added to tutorials as necessary. No need for a separate tutorial for it.
