### ISSUE TITLE
Tips and Tricks Tutorial

### ISSUE THREAD

**Issue by jnoller** [getcarina/getcarina.com#194]
@jamiehannaford inspired me!

to get the swarm discovery id for your cluster, you can run:

```
`docker inspect -f "{{index .Config.Cmd 6}}" $(docker ps -aq -f name=swarm-manager -n 1)` (edited)
```

Jamie Hannaford [5:26 AM]
@thomasem: managed to get a list of swarm nodes from that. just plug above cmd into `swarm list $(...)` (edited)

**Comment by carolynvs** [comment]
I have made aliases for some commands that I run all the time

Get the logs for the last run container. I aliased to **dl**.

```
$ docker logs -f $(docker ps -lq)
Server has started...
Now listening on http://0.0.0.0:8080
```

Get the port(s) and ip for the last run container. I aliased to **dp**.
```
$ docker port $(docker ps -lq) | cut -d " " -f3
172.99.73.31:443
172.99.73.31:80
```

**Comment by everett-toews** [comment]
`alias de='env | grep DOCKER_ | sort'`

```
$ de
DOCKER_CERT_PATH=/Users/octopus/.carina/clusters/octopus/dev
DOCKER_HOST=tcp://xxx.xxx.xxx.xxx:2376
DOCKER_TLS_VERIFY=1
DOCKER_VERSION=1.9.1
```

**Comment by carolynvs** [comment]
I put this in `~/.bash_profile`

```
docker-ssh() {
  # Try to run bash, then fallback to stinky old sh
  docker exec -it $1 /bin/sh -c "if [ -e '/bin/bash' ]; then /bin/bash; else /bin/sh; fi"
}
```

and now I can run `docker-ssh <container-name>` and jump right into an interactive shell session

**Comment by carolynvs** [comment]
Also @everett-toews just dropped this gem in chat: `unset ${!DOCKER_*}`
