### ISSUE TITLE
Linking to Carina binary

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/getcarina.com#228]
How do we link to the latest binary of `carina`, when it's released via GitHub releases?

Options:

1. Use the https://github.com/rackerlabs/carina/releases/latest URL

2. Point to an individualized URL structure for each OS? Something like getcarina.com/cli/latest/darwin/amd64/carina, etc.?

**Comment by everett-toews** [comment]
@rgbkrk This got sorted right? What was the final resolution?

**Comment by rgbkrk** [comment]
The infra is setup via download.getcarina.com. We need automation in place to ship the carina binaries in the same way as dvm then we can pull the trigger on docs too.

**Comment by carolynvs** [comment]
Closing as this is now fully automated.

**Comment by rgbkrk** [comment]
:tada:
