### ISSUE TITLE
CI/CD tutorial

### ISSUE THREAD

**Issue by zcorleissen** [getcarina/getcarina.com#23]
* CI and CD pipelines 101 (will need to be slightly opinionated)
* Accepting webhooks from Docker Hub to trigger deploy
* Rolling deployments (in a separate card)

Also assigned: @smashwilson, @everett-toews

**Comment by everett-toews** [comment]
This [ehazlett/conduit](https://github.com/ehazlett/conduit) tool hasn't been touched in 5 months but it could do what we need without have to maintain more code. 

Also, does [strider](https://github.com/Strider-CD/strider) fit into the picture here?

**Comment by everett-toews** [comment]
Users are already asking for this kind of content. Update this forum post when this issue is resolved. https://forums.docker.com/t/ci-cd-using-docker-need-suggestions-on-my-approach/4111

**Comment by jamiehannaford** [comment]
@everett-toews I can start writing this. I think we can get this working with [drone](https://github.com/drone/drone) and [watchtower](https://github.com/CenturyLinkLabs/watchtower).
