### ISSUE TITLE
Redundant articles on creds

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#378]
Do we need `_tutorials/011-carina-credentials.md` now that we have `_getting-started/003-create-connect-cluster.md` ?

IMO...no. `_tutorials/011-carina-credentials.md` should be removed and links updated to `_getting-started/003-create-connect-cluster.md`.

The `_tutorials/*-load-docker-environment-on-*.md` would be unnecessary too.

**Comment by meker12** [comment]
Noticed on the create-connect-cluster article -- when I select Autoscale for the new cluster, I get more containers, nodes, and images as shown below.  Do we want to mention that?

```docker info``` command output when Autoscale is selected: 

```
Containers: 8
Images: 6
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 2
 ca5f76f7-aae1-4f69-82a7-2c43a869acf8-n1: 104.130.0.174:42376
  └ Containers: 4
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 2.1 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
 ca5f76f7-aae1-4f69-82a7-2c43a869acf8-n2: 104.130.0.175:42376
  └ Containers: 4
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 2.1 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
CPUs: 24
Total Memory: 4.2 GiB
Name: c4213f7dd01b
```

**Comment by jnoller** [comment]
@everett-toews want @lauracly to make the call?

**Comment by everett-toews** [comment]
We actually chatted about this already. Generally opinion was, "Ya, get rid of them.". We held off because they were linked to from other content and we didn't want to risk breaking links this late in the game. I'd be willing to delete them right now though.

**Comment by kmsholcomb** [comment]
Other articles link the "load-docker-environment" articles. All of the articles in the "local Docker environment" "set" of articles are tied together through linking. If we want to get rid of them all, that's one thing; but we can't just delete some and not others without requiring re-analysis.

**Comment by lauracly** [comment]
Kelly updated the URLs and also removed old screen shots. Will leave in place for M1 but decide quickly post-launch final disposition.

**Comment by everett-toews** [comment]
@kmsholcomb Are we any closer to being able to deduplicate here?

**Comment by kmsholcomb** [comment]
I will take a look and leave a comment about the status.

**Comment by kmsholcomb** [comment]
After talking to Carolyn, I updated links to `create-connect-cluster.md` and deleted the redundant `carina-credentials` article. We decided to keep the "load" articles as part of "local Docker" path.
