### ISSUE TITLE
What to do with the Troubleshooting section?

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#380]
The Troubleshooting section can sometimes be big and cause a fair bit of noise in a tutorial. 

We could collapse it until it's explicitly clicked on. Or move it to the end of tutorials? Or move it to its own bucket and link out to it? etc.

**Comment by kmsholcomb** [comment]
Is this issue resolved by the creation of the "Troubleshooting common problems" article and the revision of the "Troubleshooting" sections in the existing tutorials? 

I added the boilerplate for the "Troubleshooting" section to the https://github.com/getcarina/getcarina.com/edit/master/_M2/_000-tutorial-task-template.md and 
https://github.com/getcarina/getcarina.com/edit/master/_M2/_000-tutorial-101-template.md templates, with instructions. That should ensure that future articles that start from templates have the standard troubleshooting information.

**Comment by everett-toews** [comment]
Works for me. The troubleshooting section is much smaller now and doesn't present a "hurdle" for the reader to get to the Next Step section.
