### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by zcorleissen** [getcarina/getcarina.com#45]
@cyrichardson: From DevEx onsite, https://docs.docker.com/articles/dockerfile_best-practices/

**Comment by rose-coste** [comment]
@zcorleissen & @lauracly: can we close this issue? 

One topic discussed here, whether to publish 1 or many best-practices articles, seems settled: 16 best-practices articles are published at https://getcarina.com/docs/; others are waiting for M2. 

Other suggestions of specific best practices can be tracked in their own issues if they still need to be written up.

**Comment by lauracly** [comment]
Yes, I am fine with closing.
