### ISSUE TITLE
"segments" vs. "nodes" inconsistency with Carina web UI and CLI

### ISSUE THREAD

**Issue by mendeni** [getcarina/getcarina.com#460]
Sometimes swarm hosts are referred to "segments", other times they're "nodes".
To align with Docker documentation and command output, can we consider using "nodes" everywhere?

**Comment by ktbartholomew** [comment]
"segments" is supposed to be the norm. Where are you seeing "nodes"?

**Comment by jnoller** [comment]
@mendeni It's a good question - the reason we used segments is that nodes implies physical separation in distributed systems, and in carina they are not, they're just additional resource chunks of a whole cluster.

**Comment by mendeni** [comment]
The Carina CLI shows Nodes:
<pre>
$ carina list
ClusterName     Flavor          Nodes   AutoScale       Status
prod04          container1-4G   5       false           active
</pre>
Docker also refers to nodes:
<pre>
$ docker info
Containers: 11
Images: 10
Role: primary
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 5
 c84e61a8-4a69-4ac9-9aa9-77edf2183866-n1: 104.130.0.23:42376
  └ Containers: 3
  └ Reserved CPUs: 0 / 12
  └ Reserved Memory: 0 B / 4.2 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.18.21-1-rackos, operatingsystem=Debian GNU/Linux 7 (wheezy) (containerized), storagedriver=aufs
...
</pre>

**Comment by jnoller** [comment]
I think the carina CLI should be changed - in Dockers case they're implying physical separation of hosts (horizontal) scale out

**Comment by jnoller** [comment]
@rgbkrk thoughts?

**Comment by jnoller** [comment]
also @simonjj - I think we should ask users what makes sense.

**Comment by rgbkrk** [comment]
Nodes comes directly from the current API. I can adjust the messaging in `carina` and ship another release.

People understand nodes from their logical point of view as a user. They're not thinking about how *we* host it, they're thinking about their apps running with their own IPs and resources.

**Comment by rosskukulinski** [comment]
From a user's point of view, I think of them as 'nodes'. Your internal structure (or naming scheme) doesn't really matter to me.

With that said however:

Is it possible for two segments of a cluster to be on the same physical host?  If so, then I understand why you went with 'segment'.  I also wouldn't understand why you would put two segments from a cluster on the same physical host, as that defeats the whole idea of spreading out applications across multiple hosts.

**Comment by jnoller** [comment]
> On Nov 20, 2015, at 4:51 PM, Ross Kukulinski <notifications@github.com> wrote:
> 
> From a user's point of view, I think of them as 'nodes'. Your internal structure (or naming scheme) doesn't really matter to me.
> 
> With that said however:
> 
> Is it possible for two segments of a cluster to be on the same physical host? If so, then I understand why you went with 'segment'. I also wouldn't understand why you would put two segments from a cluster on the same physical host, as that defeats the whole idea of spreading out applications across multiple hosts.
> 

That's the key; a cluster is a swarm cluster on one libvrt host; so it's not physically spread out; a segment contains a swarm master but given its probably on the same host as the others calling it a node isn't correct.

True fan out as you mention will require more on the docker / overlay networking and / or kubernetes to set up the interconnects

**Comment by rosskukulinski** [comment]
Interesting.  If I understand correctly, then Carina's "cluster" in its current form is nothing more than name-spacing on a physical host.  Segments are just syntactic namespacing without the benefit of isolation compared to "fan out" across physical hosts.

When you do roll out docker overlay networking and/or kubernetes, what are your thoughts on naming conventions there?  I'm not up to speed on how you plan to integrate kubernetes, but presumably you will abstract away the underlying "master(s)" and "minion(s)" from Carinia's terminology?

**Comment by jnoller** [comment]
Yeah; terminology is awkward - https://getcarina.com/docs/overview-of-carina/ since its multi tenant chunks of hosts; it gets awkward. We'll have to adapt as we iterate and add more features such as allowing for deployment to VMs or onmetal / etc

What's doubly confusing is that while most swarm deployments are 1:1 docker always uses cluster/nodes. I'm beginning to warm to the idea that "segments" was a bad call on my part and we should just let it be nodes given we're going to support this config and others

**Comment by everett-toews** [comment]
Fixed via https://github.com/getcarina/carina/pull/89
