### ISSUE TITLE
Connecting Carina Swarms to other services privately.

### ISSUE THREAD

**Issue by simonjj** [getcarina/getcarina.com#505]
People want to connect to cloud services. Wondering if something could be worked around using OpenVPN + VM Instance + Ambassador + Carina?

**Comment by jnoller** [comment]
Document servicenet functionality available

**Comment by jnoller** [comment]
Will work on 10/30

**Comment by jnoller** [comment]
Carina Networking tutorial

**Comment by everett-toews** [comment]
This is @rgbkrk's handy dandy racknet/ip image. We'll want to mover that to carina or carinamarina on Docker hub later next week.

`docker run --net=host racknet/ip service` returns the ServiceNet IPv4 address
`docker run --net=host racknet/ip public` returns the public IPv4 address

Get help using the util.

```
$ docker run --net=host racknet/ip --help
racknet public [ipv4|ipv6]
racknet service [ipv4|ipv6]

Examples:
          $ racknet public
          104.130.0.127

          $ racknet service ipv6
          fe80::be76:4eff:fe20:b452

Examples when run with Docker:
          $ docker run --net=host racknet/ip public
          104.130.0.127
```

**Comment by jnoller** [comment]
Blogged here: https://getcarina.com/blog/news-and-networking/ need to add a tutorial
