### ISSUE TITLE
Update carina cli page with `brew` instructions

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/getcarina.com#508]
Now that we have `brew install carina` available, we should provide that on https://getcarina.com/docs/getting-started/getting-started-carina-cli/. Also, chocolatey based installs have been good for a while thanks to @carolynvs. We should include both in the cli page.

**Comment by carolynvs** [comment]
FYI, the Chocolatey package is still stuck in moderation... I've pinged them on gitter and I'll report back if I hear anything.

**Comment by rgbkrk** [comment]
Ohhh yeah, I'm a bit forgetful. Sorry!

**Comment by carolynvs** [comment]
Both rack and carina have passed their automated testing but I'm still waiting for them to be released from moderation.

**Comment by rgbkrk** [comment]
Maybe I should just make this one about `brew` and we make a new one about chocolatey.

**Comment by carolynvs** [comment]
Yeah... I have no idea when they are going to finally get around to approving. They are in the middle of automating the moderation process, so in the future this shouldn't suck so hard. :smile:

**Comment by carolynvs** [comment]
I've made a #585 and given this back to @rgbkrk to wrap up for brew.
