### ISSUE TITLE
Doc dvm and carina CLI in the Create and connect to a cluster tutorial

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#514]
As soon as dvm is 100% ready to go, document it's use in the Create and connect to a cluster tutorial. Document use of the Carina CLI in the Create and connect to a cluster tutorial too.

Some open questions.

How do we best present the choice of GUI or CLI in the tutorial?
How does it fit in with the Getting Started and Getting Started with the CLI guides?

**Comment by carolynvs** [comment]
I'm working on this from the dvm side in PR #537
