### ISSUE TITLE
Prefix all links with {{ site.baseurl }}

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#520]

**Comment by kmsholcomb** [comment]
I added this requirement to the link guideline in Contributing.md. However, that doesn't address the fact that the majority of existing links do *not* use `{{site.baseurl}}`.

**Comment by lauracly** [comment]
@ktbartholomew @everett-toews what is the next step here - should I go into all of the articles and add this?

**Comment by ktbartholomew** [comment]
@lauracly I'll write a little script to take care of this.

**Comment by lauracly** [comment]
Sounds good to me - thanks Keith.

**Comment by rgbkrk** [comment]
D'oh! I'm an offender here.
