### ISSUE TITLE
Remove number prefix from all files

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#521]
The whole number prefix in the files is pretty nasty. Let's investigate alternatives with @ktbartholomew.

**Comment by rose-coste** [comment]
Yes. Today I'm likely taking down one of the best-practices articles, currently numbered 002. So that leaves 001 and 003 - 016. I'm assuming that gap in the sequence won't cause a problem in presenting the remaining articles at https://getcarina.com/docs/, but it seems safer to stop numbering.

**Comment by ktbartholomew** [comment]
How is the correct order of articles determined? When new articles are added, how is their position in the series determined?

**Comment by rose-coste** [comment]
I think @lauracly determined the current order. I don't know of a process for revising the order as new ideas come along and old ideas fade out.

**Comment by lauracly** [comment]
@everett-toews @kmsholcomb and I determined the order and used the numbers to get the articles to appear in that order.  Right now if a new article is added say at spot 3, then everything after 3 has to get renumbered (not great approach but it works). We left some gaps in between the article types to lessen the renumbering impact, but a better mechanism would be great.

**Comment by rose-coste** [comment]
so in /best-practices/, I really am getting ready to delete 002 right now. I must then renumber 003 - 016 to become 002 - 015?

**Comment by ktbartholomew** [comment]
Sounds like a job for a shell script!

Since the idea of numbering them is on the chopping block, leaving a gap is probably fine.

**Comment by lauracly** [comment]
@ktbartholomew will this require a code change since we use the numbers to keep the articles in a certain order today? Can you accommodate this work in the next few weeks?

**Comment by ktbartholomew** [comment]
Yes, if we just remove the numbers, the order of all the posts would change. I'll get a PR going for a way to sort without the numbered files and we can continue the implementation discussion there.
