### ISSUE TITLE
Relocate content into new directories (buckets)

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#522]
Suggested buckets

* concepts
* tutorials
* getting-started
* troubleshooting
* reference
* rename best-practices to whitepapers

**Comment by metral** [comment]
* best-practices / whitepapers should actually be "General Guide to Container Ecosystem"

**Comment by lauracly** [comment]
@ktbartholomew @everett-toews We discussed the proposed buckets. Did we ever come to a consensus? I wanted to get this issue and the URL ones done before too much new content is created.

**Comment by everett-toews** [comment]
* tutorials
* getting-started
* troubleshooting
* reference
* ecosystem (best-practices renamed)

**Comment by kmsholcomb** [comment]
The attached spreadsheet lists the current articles and which buckets to put them in. Let me know if you have any questions. Thanks!

[Carina buckets.xlsx](https://github.com/getcarina/getcarina.com/files/58402/Carina.buckets.xlsx)

**Comment by kmsholcomb** [comment]
Note that the spreadsheet does not list the current best practices articles, which will all just be put into the new "ecosystem" bucket.
