### ISSUE TITLE
tutorial needed: basic routing / networking

### ISSUE THREAD

**Issue by jnoller** [getcarina/getcarina.com#534]
![screen shot 2015-11-10 at 9 12 48 am](https://cloud.githubusercontent.com/assets/51528/11065877/548841f6-878b-11e5-93c4-2bd759de8d33.png)

tl;dr "how can I route network from the internet into my containers? where do I get the public IP? (I didn't find anything in the docs or api)" 

A: You can also use docker port <container_id> to get the ip for that container
As well as docker info to get the public IPs of all the docker hosts in your swarm cluster

Companion links:
https://community.getcarina.com/t/region-selection-and-servicenet-support/38/4
https://getcarina.com/docs/tutorials/servicenet/

**Comment by everett-toews** [comment]
https://getcarina.com/docs/tutorials/servicenet/

https://getcarina.com/docs/tutorials/overlay-networks/

Reopen if more information is required.
