### ISSUE TITLE
Links to sections should not display a paragraph tag

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#559]
New linking capability causes a paragraph symbol to display in front of every "linkable" heading. These symbols shouldn't display, and only the heading should appear clickable.

**Comment by lauracly** [comment]
Hi everyone - evan is back in the office next week and can provide the UX perspective on this request. Just FYI.

**Comment by carolynvs** [comment]
I like @ktbartholomew 's suggestion to use the standard font-awesome link icon #594. The paragraph symbol is confusing.

**Comment by everett-toews** [comment]
This is fixed.
