### ISSUE TITLE
Create a tutorial for IRC bouncer

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#566]

**Comment by everett-toews** [comment]
[Using Carina to Mimic IRCcloud](http://jjasghar.github.io/blog/2015/11/15/using-carina-to-mimic-irccloud/)

**Comment by rgbkrk** [comment]
Seems like a good thing for the Carina Weekly too!

**Comment by kenperkins** [comment]
:+1:

**Comment by zack-shoylev** [comment]
I am working on a guide that uses Quassel as the "bouncer"
