### ISSUE TITLE
Fallout 4 Blog Posts

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/getcarina.com#572]
There will be at least four Fallout 4 posts, starting with the first that already went out (#556):

* [X] Fallout 4 Service Discovery and Relays
* [X] Community of Vault Dwellers across languages (#574)
* [ ] Reactive programming the pipboy from Fallout 4 with RxJS
* [ ] Setting up a Beacon to share your pipboy data from Fallout 4

**Comment by lauracly** [comment]
Hey there - just checking in. Are you continuing this series of posts? Is there a target date for the third post?

**Comment by rgbkrk** [comment]
I went deep into Frontend dev for the third post and ending up encompassing the fourth post while I was at it. I'm currently breaking it apart into some decent narratives now.

**Comment by lauracly** [comment]
Moving to M2 to allow more time to complete final 2 posts.

**Comment by rgbkrk** [comment]
I'm going to repurpose "Setting up a Beacon to share your pipboy data from Fallout 4" to be the more generic tutorial on setting up PKI between two containers.
