### ISSUE TITLE
Using RCS with ASP.NET 5

### ISSUE THREAD

**Issue by zcorleissen** [getcarina/getcarina.com#6]
ASP.NET 5 can run on Linux but most .NET devs aren't familiar enough with Linux to know how to deploy or run their server. RCS would work well in this situation as the entire process can be mediated through familiar tools Visual Studio and VS Online.

* How to test on a local docker container running linux from your windows dev box
* Deploy from Visual Studio to your local machine
* Deploy directly to RCS
* CI/CD
    * Build a docker image using VSO
    * Publish to docker hub
    * Deploy to staging
    * Deploy to production

**Comment by carolynvs** [comment]
@everett-toews FYI, I am working on this now and it is shaping up to be a series of articles. Should I make separate issues for each chunk of content that I'm thinking of?

* install asp.net and publish a site to carina using windows + visual studio (the old fashioned way)
* install asp.net and publish a site to carina using any platform and the command line (new hotness)
* how to test and debug using a local docker host
* the ci/cd aspect and how to integrate Visual Studio Online with Carina

**Comment by carolynvs** [comment]
I think splitting up is the right way to do this. I'm going to make the issues from my last comment and then close this one.

**Comment by everett-toews** [comment]
:+1: 

(sorry I missed the earlier ping)
