### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#608]
After #522 some content should have been published to new URLs.

e.g.
https://github.com/getcarina/getcarina.com/blob/master/_reference/2015-10-18-faq.md published to https://getcarina.com/docs/reference/faq/

https://github.com/getcarina/getcarina.com/blob/master/_reference/2015-10-17-release-notes.md published to https://getcarina.com/docs/reference/release-notes/

But we get 404s for both pages. Not sure if it's isolated to the reference bucket. We'll need to run a dead link checker on both getcarina.com and community.getcarina.com.

**Comment by smashwilson** [comment]
I'm not seeing references to the metadata envelopes for those files in the [latest build output](https://travis-ci.org/getcarina/getcarina.com/builds/96365790). Are we missing some kind of configuration flag to build them... ?

**Comment by everett-toews** [comment]
http://www.brokenlinkcheck.com/ seems to do a decent job of reporting on broken links.

<img width="551" alt="screen shot 2015-12-14 at 10 27 50 am" src="https://cloud.githubusercontent.com/assets/634901/11786684/790bd7e0-a24d-11e5-9edc-c772e37a2559.png">
