### ISSUE TITLE
I get "Error response from daemon: 500 Internal Server Error: database or disk is full"

### ISSUE THREAD

**Issue by dalareo** [getcarina/getcarina.com#617]
My cluster suddenly stop to work. I cannot backup my container data creating a new volume because I get the message above.
If I try to start the stopped container again I get: 
    Error response from daemon: Cannot start container c83265b6622c184c4c72121fd63b8348502df3eddc79cf51c17146963ba55f55: container already connected to network bridge

**Comment by coreypobrien** [comment]
The "database or disk is full" error is likely due to your local disk being full. Unfortunately docker doesn't provide any good way to see local disk usage through the API, but if you have any cleanup you can do of old images or volumes that may unblock you enough to get the backup done to external data storage.

**Comment by dalareo** [comment]
Ok. Thanks. How much space can be allocated?

**Comment by everett-toews** [comment]
You get 20 GB of disk space per segment, see [What resources does a single cluster have?](https://getcarina.com/docs/reference/faq/#what-resources-does-a-single-cluster-have).

**Comment by dalareo** [comment]
I was using two segments... and absolutely no more than 10gb. Anyway I couldn't save my container data...

**Comment by everett-toews** [comment]
@dalareo If it happens again, do a `docker info` on your cluster and let us know that info so we can help find out how your disk space is getting used up.

Disk space isn't exposed by the Docker API so we're not exactly sure how we're going to expose this info yet. It's being tracked in the issue [Disk stats](https://github.com/getcarina/feedback/issues/33).
