### ISSUE TITLE
Verbiage for non-Racker contributors

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#633]
We have our first guest blog post in PR #630!

We should display some verbiage at the top of such posts, conditional on `authorIsRacker: false` that mentions the author awesome but not a Racker yada yada yada.

**Comment by ktbartholomew** [comment]
What's the motivation behind explicitly stating that the author isn't a Racker?

**Comment by rgbkrk** [comment]
Stating 'Guest post' makes sense to me and certainly friendlier than "non-Racker"

**Comment by rgbkrk** [comment]
A carinaut, like an astronaut?

/me shows himself out

**Comment by lauracly** [comment]
Guest post is my preference. @kmsholcomb agree?

**Comment by ktbartholomew** [comment]
**This post was contributed by a member of the Carina community** Are you doing something awesome with Carina that you'd like the world to know about? Share it here! [learn how](https://github.com/getcarina/getcarina.com/blob/master/CONTRIBUTING.md)

**Comment by everett-toews** [comment]
Works for me. @kmsholcomb gets the final call.

**Comment by kmsholcomb** [comment]
Um, I suppose I'd like to see whatever verbiage we are suggesting in context. If we just have a label like "Guest post," where would that go? Or, if we have a paragraph like Keith suggests, where would we place it? I wouldn't think that we'd want to put much extra text at the top of the article. It seems like we'd want something "labelish" and brief at the top, maybe next to the author's name, and then something like Keith suggests at the end of the article (at least as far as soliciting content from others).

**Comment by ktbartholomew** [comment]
If we're trying to strengthen the credibility and active-community-warm-fuzzies of the post, a brief caveat at the beginning is the place to do it. The reality of the web is that most people aren't going to read our posts all the way to the end, so explaining that it's a guest post at the end will add very little value.

A "label" would just go inline next to the author's name and would be very out-of-the-way, but would be easy to miss and not give us the opportunity to convert readers into future contributors.

I'll work with RED to figure out the visual details, but we'll need to know that our copy is final before doing that.

**Comment by kmsholcomb** [comment]
Thanks for the explanation and context! I'm fine with the proposed wording, although I suppose I'd suggest a couple little tweaks:

**This post was contributed by a member of the Carina community**. Are you doing something interesting with Carina that you'd like to tell the world about? Share it here! [Learn how](https://github.com/getcarina/getcarina.com/blob/master/CONTRIBUTING.md).

**Comment by ktbartholomew** [comment]
Thanks @kmsholcomb!
