### ISSUE TITLE
Many broken links on FAQ page

### ISSUE THREAD

**Issue by rosskukulinski** [getcarina/getcarina.com#641]
Reading through your [FAQ](https://getcarina.com/docs/reference/faq/), it seems that many of your links are broken.  For example, the link "Connect containers with Docker links", directs people to the following URL:

https://getcarina.com/docs/reference/faq/%7B%7B%20site.baseurl%20%7D%7D/docs/tutorials/connect-docker-containers-with-links/#connect-two-containers-with-a-docker-link

**Comment by lauracly** [comment]
Hi there - yes I see what you are talking about. Thanks for pointing this out, and we will get it corrected as quickly as we can.
