### ISSUE TITLE
Tutorial for using Let's Encrypt certificates with nginx

### ISSUE THREAD

**Issue by smashwilson** [getcarina/getcarina.com#652]
Write a tutorial that covers:

* Using the official [Let's Encrypt](https://letsencrypt.org/) Docker image to issue certificates for your domain.
* Storing your certificates in a data volume container to make them available for backups and recovery.
* Building an nginx container that mounts the data volume and uses it to terminate TLS that gets an A rating from SSLLabs.
* Scheduling automatic certificate updates.

Part of getcarina/getcarina.com#573.

**Comment by smashwilson** [comment]
The nginx and Apache guides for Letsencrypt will be identical up to point 3 there. Should we `_include` that as common content?

**Comment by everett-toews** [comment]
If doing an `_include` works out, great.

For the backup and recovery, we should try to have it work with [cf-backup](https://hub.docker.com/r/carinamarina/cf-backup/) and [cf-restore](https://hub.docker.com/r/carinamarina/cf-restore/).
