### ISSUE TITLE
Carina UI not fully functional on Internet Explorer 10: Built clusters are not visible

### ISSUE THREAD

**Issue by stanzikratel** [getcarina/getcarina.com#663]
When you try to add a cluster in IE 10, you cannot see how the cluster is built and also cannot access the built cluster.
I did an **Add Cluster** in IE 10 today and specified the relevant cluster information. When I clicked **Create Cluster**, the UI went back to **Add Cluster** and it appeared as if my cluster wasn't building. I then checked my account in Firefox and saw that my cluster had built.

Need to fix this or add a disclaimer and maybe also note in the Docker on Windows document that the Carina UI doesn't fully work in IE (I tested on IE 10).

**Comment by carolynvs** [comment]
IE10 isn't supported anymore by microsoft, so I don't think we should target it. However, I just tested on IE11, and it is broken there as well. Even after logging out and in again, I don't see the new cluster, even though it is present and active.

I also discovered that when you log out, you can't log in as another user. It keeps logging me in as my previous user. I assume all of this is a buggy IE cache, as clearing it fixes both problems. @ktbartholomew  This seems like a nasty bug, letting me log in as someone who just logged out...

**Comment by ktbartholomew** [comment]
Could one of you send a screenshot or gif of the problem @stanzikratel described?

**Comment by carolynvs** [comment]
I'll get that in a bit.

**Comment by carolynvs** [comment]
Here you can see that new clusters don't show up, even after refreshing the page.

![add-cluster-ie11](https://cloud.githubusercontent.com/assets/1368985/12755966/2d359cb8-c997-11e5-97f4-d78f023330e7.gif)

Here you can see that when I log out and log in as another user, it logs me in as the previous user, and still doesn't show the new cluster either. Clearing the cache fixes it.

![logout-login-ie11](https://cloud.githubusercontent.com/assets/1368985/12756083/bae534ba-c997-11e5-90bd-6bc71f2171c0.gif)

**Comment by ktbartholomew** [comment]
We'll look at this as part of the make-coe developement work.
