### ISSUE TITLE
Web UI does not handle additional segments

### ISSUE THREAD

**Issue by rosskukulinski** [getcarina/getcarina.com#665]
I requested (and received) an increase in the max-segments for my clusters.  The main dashboard seems to only ever display a maximum 3 segments.  Looking at the cluster details, however, it does show the increased number of segments.

**Comment by ktbartholomew** [comment]
To support this, we would need to present a `node_limit` property in the make-swarm API. Currently no data on limits is provided, so we just assume it's 3.

/cc @thomasem
