### ISSUE TITLE
Need raw plugin for easy code escaping

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#667]
ala https://github.com/rackerlabs/docs-developer-blog/blob/master/_plugins/raw.rb

It would be very helpful for https://github.com/getcarina/getcarina.com/issues/662

**Comment by carolynvs** [comment]
We are already using raw and endraw on getcarina. See step 2 in https://github.com/getcarina/getcarina.com/blob/master/_tutorials/2015-10-11-connect-docker-containers-with-links.md and it's rendered just right: https://getcarina.com/docs/tutorials/connect-docker-containers-with-links/

**Comment by ktbartholomew** [comment]
I don't think there's need for a plugin, as this functionality is built-in to Liquid: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#tags

**Comment by everett-toews** [comment]
Trying ... https://github.com/getcarina/getcarina.com/pull/668

**Comment by everett-toews** [comment]
raw to the rescue
