### ISSUE TITLE
Allow > 3 clusters to be created via UI

### ISSUE THREAD

**Issue by mdarby** [getcarina/getcarina.com#701]
The UI doesn't support the creation of clusters > 3, but the carina cli works fine.

**Comment by mdarby** [comment]
(from https://community.getcarina.com/t/capacity-requests/22/3)

**Comment by rgbkrk** [comment]
:boom: @carolynvs we win!!! :boom:

**Comment by ktbartholomew** [comment]
Duplicate of https://github.com/getcarina/getcarina.com/issues/665
