### ISSUE TITLE
Content Refresh Tracking - Kelly Holcomb

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#713]
Here is the list of articles to review:

- [x] create-connect-cluster.md	Create and connect to a cluster
- [x] glossary.md	Carina glossary

**Comment by everett-toews** [comment]
@kmsholcomb Can you give this a look this week or next?

**Comment by kmsholcomb** [comment]
Yep! Was planning to do it tomorrow.

**Comment by kmsholcomb** [comment]
Updated both articles, via https://github.com/getcarina/getcarina.com/pull/744 and https://github.com/getcarina/getcarina.com/pull/745.
