### ISSUE TITLE
Content Refresh Tracking - Stephanie Fillmon

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#716]
Here is the list of articles to review:

[ ] containers-101.md	Containers 101
[ ] service-discovery-101.md	Service discovery 101
[ ] nuke-a-container.md	How to stop a non-responsive running container

**Comment by stephamon** [comment]
@lauracly all three of mine seem okay. Two are conceptual about containers and service discovery without any command usage for Carina, and the third uses docker to stop a non-responsive container. I double checked docker's site, and none of the commands have changed there.

**Comment by lauracly** [comment]
Great - then please close this issue and also mark off as complete on the epic.
