### ISSUE TITLE
Content Refresh Tracking - Bill Anderson

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#718]
Here is the list of articles to review:
- [x] data-stores-redis.md	Use Redis on Carina

**Comment by everett-toews** [comment]
@therealbill Would you like to update this or should we take it?

**Comment by therealbill** [comment]
@everett-toews You can take it. I doubt anything needs to change but sadly haven't had time lately to keep up w/the Carina improvements y'all have been making.

**Comment by everett-toews** [comment]
We'll definitely need to make a change as we can add an additional layer of security by putting Redis on a network and not expose it to the Internet or ServiceNet. I'll take it.

**Comment by therealbill** [comment]
Ah I see. Nice new feature. :) :+1:
