### ISSUE TITLE
Content Refresh Tracking - Kyle Kelley

### ISSUE THREAD

**Issue by lauracly** [getcarina/getcarina.com#719]
Here is the list of articles to review:

* [x] interlock-on-carina.md	Run interlock on Carina

**Comment by rgbkrk** [comment]
Ooooh, yeah that probably needs a refresh as well as some software time to make interlocarina have parity with interlock.

**Comment by lauracly** [comment]
@rgbkrk can you get this review done this week?

**Comment by rgbkrk** [comment]
Updated in #752, making sure the tutorial still works (it does).
