### ISSUE TITLE
How to redirect an outdated article to new content?

### ISSUE THREAD

**Issue by carolynvs** [getcarina/getcarina.com#732]
I have two tutorials that we have linked to in the past, e.g. https://getcarina.com/docs/tutorials/connect-docker-containers-with-links/. Now that we have overlay networks, the content is out of date and not recommended anymore.

I would like to keep the page and replace the content in it with a message to go read up on overlay networks. I do not want the page to show up on the docs collection anymore however, since it's just a redirect/placeholder at this point.

Some things I have tried:
* :x:  Adding `published: false` and `output: false` in the front matter. This had no impact because we are on Jekyll 2.5 and those are from 3.0.
* :x: Prefixing the filename with an underscore. The page is no longer generated at all.
* :white_check_mark:  Moved the files into a new directory, e.g. `placeholder-redirects`. The page is still generated but isn't listed. I think this works for my purposes but would like a sanity check before going down that path.

/cc @ktbartholomew Are you okay with the last option? Or should I hold off for another solution?

**Comment by everett-toews** [comment]
Can we just remove those tutorials and do regular redirects with deconst?

@carolynvs Would you be okay with that?

**Comment by ktbartholomew** [comment]
Oh, I don't know why I didn't think of just doing a few redirects. I'd much rather do that.

**Comment by carolynvs** [comment]
Sure! Where should the redirects be defined? In nexus-control?

**Comment by ktbartholomew** [comment]
Yeah: https://github.com/rackerlabs/nexus-control/blob/master/config/rewrites.d/getcarina.com.json

**Comment by carolynvs** [comment]
Thanks guys!
