### ISSUE TITLE
Broken image (getcarina.com/docs/overview-of-carina)

### ISSUE THREAD

**Issue by mdarby** [getcarina/getcarina.com#738]
![overview of carina carina by rackspace 2016-03-03 09-30-27](https://cloud.githubusercontent.com/assets/2805/13497309/a6c3c008-e122-11e5-8bea-77f3976a8536.png)

**Comment by ktbartholomew** [comment]
![image](https://cloud.githubusercontent.com/assets/3018940/13497439/e0208e06-e11a-11e5-8c14-0aa5610b6874.png)

looks fine to me

**Comment by mdarby** [comment]
hrm odd. A few refreshes kicked it into gear.
