### ISSUE TITLE
Data backup tutorial

### ISSUE THREAD

**Issue by ktbartholomew** [getcarina/getcarina.com#746]
We should create a tutorial outlining the techniques necessary to take regular backups of data volume containers and store them somewhere less volatile than Carina. We could use a technique similar to the [cron container in NGINX/Let's Encrypt](https://getcarina.com/docs/tutorials/nginx-with-lets-encrypt/#reissue-certificates-with-a-cron-container) to connect directly to the data volume containers, `docker cp` the contents, tarball them, then use `rack` or vanilla cURL to upload them to Cloud Files.

* [x] Be tiny (based on Alpine)
* [x] Support backing up multiple volumes
* [x] Support saving backup directly to client instead of uploading to CF
* [x] Write tutorial content for doing backup/restore
* [ ] Write tutorial content for scheduling container runs and other tasks.
* [ ] Replace https://getcarina.com/docs/tutorials/quassel-on-carina/#automatically-back-up-your-data-and-restore-it-as-necessary section with links to aforementioned tutorials.

**Comment by everett-toews** [comment]
We also need to consider where the [cf-backup](https://hub.docker.com/r/carinamarina/cf-backup/~/dockerfile/) and [cf-restore](https://hub.docker.com/r/carinamarina/cf-restore/~/dockerfile/) images fit into this. Likely they should be the images this tutorial is based on. 

But let's do a proper job of fitting this altogether. Note that `rack` is now statically linked via https://github.com/rackspace/rack/commit/8fed4ac5d9a38d2c496cf833311f01ae2d1a2b90

So now a `rack` image can be `FROM alpine:3.3` and that image would live in https://hub.docker.com/u/rackspace/

Then for cf-backup and cf-restore you'd so something like `FROM rackspace/rack:1.2.0` and build on that.

/cc @zack-shoylev

**Comment by everett-toews** [comment]
We'd also want to update [data-volume-containers.md](https://github.com/getcarina/getcarina.com/blob/master/_tutorials/2015-10-23-data-volume-containers.md) to point to this tutorial, maybe as a Next step.

**Comment by zack-shoylev** [comment]
Ah good. This means the cf- images should be updated with the static link, at least.

**Comment by everett-toews** [comment]
This tutorial also needs to include a backup to local machine section.

**Comment by jnoller** [comment]
We need an option if they do not have a full rackspace account too
