### ISSUE TITLE
s/segment/node/

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#774]
It's looking pretty unanimous in https://github.com/getcarina/feedback/issues/54

We will need to be explicit about the nature of the physical location of Carina nodes in [this section](https://getcarina.com/docs/concepts/docker-swarm-carina/#carina-segments). As in, a Carina node is not necessarily running on a separate physical host.

**Comment by carolynvs** [comment]
@rgbkrk is already 12 steps ahead of you, https://github.com/getcarina/carina/pull/99 was just merged. THE PEOPLE HAVE SPOKEN! :smile:

**Comment by everett-toews** [comment]
@carolynvs PR https://github.com/getcarina/carina/pull/99 was for the carina CLI. This issue is for the grand renaming throughout the getcarina.com docs.

**Comment by carolynvs** [comment]
Yup, I know, don't mind me.  I was just making a dumb joke about the "pretty unanimous" part because people are already going off and switching segment->node.

**Comment by rgbkrk** [comment]
/me whistles

_Totally not motivated by the fact that @smashwilson and I gave a workshop today._
