### ISSUE TITLE
[Tutorial] PKI between services

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/getcarina.com#780]
The fourth bullet in https://github.com/getcarina/getcarina.com/issues/572 lists:

> Setting up a Beacon to share your pipboy data from Fallout 4

I originally got this outlined and prototyped in [beacon](https://github.com/RobCoIndustries/beacon) as:

* Generate public and private key pairs for communicating with another service
* Launch that service with strict PKI
* Communicate back and forth with it

This is more general than Beacon though. We can put together a decent tutorial that shows how to use your own private certs between two services (in beacon it's node.js <---> Go).

**Comment by everett-toews** [comment]
Is this a tutorial or blog post?

It looks to me like beacon is a Fallout specific thing and the other Fallout stuff were posts too. Does it make sense to keep it as a series of blog posts?

**Comment by rgbkrk** [comment]
Tutorial. I want to at least extract out the PKI parts (not talk about Beacon).

**Comment by rgbkrk** [comment]
Updated the summary to adjust. Basically, Beacon was going to be my narrative piece (for a blog post) while the underlying tech is boring, simple, and people should know how to use it.

**Comment by rgbkrk** [comment]
I've now made sure the code is sound for both the raw tcp and the https case here: https://github.com/rgbkrk/pki-examples

Blog post to be written during my flight and layover tomorrow.

**Comment by kimtryce** [comment]
Closing this out since Kyle is now a Netflixer.
