### ISSUE TITLE
Weekly News: June 3

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#861]

**Comment by everett-toews** [comment]
https://getcarina.com/docs/reference/release-notes/#may-23-2016

**Comment by everett-toews** [comment]
PyCon: http://getcarina.github.io/jupyterhub-tutorial/slides/

**Comment by kimtryce** [comment]
I'll own this week's weekly.  Thanks for the notes @everett-toews

**Comment by kimtryce** [comment]
https://github.com/getcarina/getcarina.com/pull/866
