### ISSUE TITLE
what is the "docker host"?

### ISSUE THREAD

**Issue by josefinb** [getcarina/getcarina.com#877]
"Otherwise, run docker-machine env default --shell cmd, replacing default with the name of your Docker host"

what is the docker host?

Thanks in advance!

**Comment by carolynvs** [comment]
@josefinb In the context of the instructions above, "docker host" refers to the name of the docker machine that you created earlier.

In the example below, I am creating a domain machine named "foobar".

```
docker-machine create foobar --driver virtualbox
docker-machine env foobar --shell cmd
```

**Comment by josefinb** [comment]
Thanks, that worked!
